"""
config.py — Central configuration for the Campus Assistant backend.

All tunable values (paths, model settings, hyperparameters) live here.
Other modules import from this file so you only need to change one place.
"""

import os

# Load .env from backend root so GROQ_API_KEY and other secrets are available
try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))
except ImportError:
    pass  # python-dotenv not installed — rely on shell environment

# ── Paths ─────────────────────────────────────────────────────────────────────

# Base directory of this backend folder (works regardless of where you run from)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Path to the JSON campus knowledge base
# Env var KB_PATH overrides the default (useful inside Docker)
KB_PATH = os.getenv("KB_PATH", os.path.join(BASE_DIR, "data", "campus_kb.json"))

# Path to the synthetic FAQ training dataset
CSV_PATH = os.getenv("CSV_PATH", os.path.join(BASE_DIR, "data", "faq_dataset.csv"))

# Where the fine-tuned DistilBERT model will be saved after training
MODEL_SAVE_DIR = os.getenv("MODEL_SAVE_DIR", os.path.join(BASE_DIR, "models", "intent_classifier"))

# ── Phase 3: CLIP + FAISS image retrieval ────────────────────────────────────

# HuggingFace model ID for the CLIP vision-language encoder
CLIP_MODEL_NAME = "openai/clip-vit-base-patch32"

# Pre-built FAISS index — generated by src/build_image_index.py
FAISS_INDEX_PATH = os.getenv("FAISS_INDEX_PATH", os.path.join(BASE_DIR, "models", "faiss_kb.index"))

# JSON file mapping FAISS row index → campus KB record dict
FAISS_ID_MAP_PATH = os.getenv("FAISS_ID_MAP_PATH", os.path.join(BASE_DIR, "models", "faiss_id_map.json"))

# Cosine similarity threshold below which we treat the match as "no result"
IMAGE_MATCH_THRESHOLD = 0.25

# Number of top FAISS candidates to return per image query
IMAGE_TOP_K = 3

# ── Model Settings ────────────────────────────────────────────────────────────

# The pretrained HuggingFace model we fine-tune from.
# distilbert-base-uncased is smaller and faster than full BERT,
# which makes it ideal for a laptop/CPU academic project.
BASE_MODEL = "distilbert-base-uncased"

# Maximum number of tokens per input sentence.
# Campus queries are short, so 64 is more than enough and keeps training fast.
MAX_LENGTH = 64

# ── Training Hyperparameters ──────────────────────────────────────────────────

# Number of training examples processed together in one forward/backward pass.
BATCH_SIZE = 16

# How many times to iterate over the full training set.
EPOCHS = 15

# How fast the model updates its weights. 2e-5 is the standard DistilBERT
# fine-tuning learning rate recommended by the HuggingFace team.
LEARNING_RATE = 2e-5

# Random seed for reproducibility — ensures the same results every run.
SEED = 42

# ── Intent Labels ─────────────────────────────────────────────────────────────

# The five categories of user questions the model learns to classify.
INTENT_LABELS = [
    "find_location",    # "Where is the library?"
    "ask_hours",        # "What time does the gym close?"
    "find_event",       # "Are there any events this week?"
    "find_department",  # "Where is the CS department?"
    "find_study_area",  # "Where can I study quietly?"
    "find_navigation",  # "How do I get from A to K?" / "Directions to the gym"
]

# Maps intent string → integer index (used when training the classifier head)
LABEL2ID = {label: idx for idx, label in enumerate(INTENT_LABELS)}

# Maps integer index → intent string (used when interpreting model output)
ID2LABEL = {idx: label for idx, label in enumerate(INTENT_LABELS)}

# Convenience alias used by notebooks and fusion_mlp demos
LABELS = INTENT_LABELS

# Minimum softmax confidence below which the model says "I didn't understand"
CONFIDENCE_THRESHOLD = 0.5

# ── Groq LLM ──────────────────────────────────────────────────────────────────

# API key loaded from .env (do NOT hardcode)
# Accepts both GROQ_API_KEY and GROK_API_KEY (common typo in .env files)
GROQ_API_KEY = os.getenv("GROQ_API_KEY") or os.getenv("GROK_API_KEY", "")

# LLaMA 3 8B is fast and free-tier friendly; swap to "llama3-70b-8192" for higher quality
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant")

# Set to False to disable LLM and use template responses (useful for offline testing)
USE_LLM = os.getenv("USE_LLM", "true").lower() == "true"

# Below this DistilBERT confidence, ask Groq to validate/refine the intent
LLM_INTENT_THRESHOLD = 0.75
